# Generated by Django 5.2.6 on 2025-09-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=50)),
                ('std_class', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
